package com.sysm.back.dao;

import com.sysm.back.model.ProductKind;
import com.sysm.back.model.ProductKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int countByExample(ProductKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int deleteByExample(ProductKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int insert(ProductKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int insertSelective(ProductKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    List<ProductKind> selectByExample(ProductKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    ProductKind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductKind record, @Param("example") ProductKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductKind record, @Param("example") ProductKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductKind record);
}