package com.sysm.back.model;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.period
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.purchase_price
     *
     * @mbggenerated
     */
    private Integer purchasePrice;
    private String purchasePriceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.original_price
     *
     * @mbggenerated
     */
    private Integer originalPrice;
    private String originalPriceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.difference_price
     *
     * @mbggenerated
     */
    private Integer differencePrice;
    private String differencePriceStr;

    public void setPurchasePriceStr(String purchasePriceStr) {
        this.purchasePriceStr = purchasePriceStr;
    }

    public void setOriginalPriceStr(String originalPriceStr) {
        this.originalPriceStr = originalPriceStr;
    }

    public void setDifferencePriceStr(String differencePriceStr) {
        this.differencePriceStr = differencePriceStr;
    }

    public String getPurchasePriceStr() {
        return purchasePriceStr;
    }

    public String getOriginalPriceStr() {
        return originalPriceStr;
    }

    public String getDifferencePriceStr() {
        return differencePriceStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.discount_price
     *
     * @mbggenerated
     */
    private Integer discountPrice;
    private String discountPriceStr;

    public void setDiscountPriceStr(String discountPriceStr) {
        this.discountPriceStr = discountPriceStr;
    }

    public String getDiscountPriceStr() {
        return discountPriceStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.is_effective
     *
     * @mbggenerated
     */
    private Integer isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.spread_url
     *
     * @mbggenerated
     */
    private String spreadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_id
     *
     * @mbggenerated
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.product_id
     *
     * @return the value of activity.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.product_id
     *
     * @param productId the value for activity.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.product_name
     *
     * @return the value of activity.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.product_name
     *
     * @param productName the value for activity.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.period
     *
     * @return the value of activity.period
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.period
     *
     * @param period the value for activity.period
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.purchase_price
     *
     * @return the value of activity.purchase_price
     *
     * @mbggenerated
     */
    public Integer getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.purchase_price
     *
     * @param purchasePrice the value for activity.purchase_price
     *
     * @mbggenerated
     */
    public void setPurchasePrice(Integer purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.original_price
     *
     * @return the value of activity.original_price
     *
     * @mbggenerated
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.original_price
     *
     * @param originalPrice the value for activity.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.difference_price
     *
     * @return the value of activity.difference_price
     *
     * @mbggenerated
     */
    public Integer getDifferencePrice() {
        return differencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.difference_price
     *
     * @param differencePrice the value for activity.difference_price
     *
     * @mbggenerated
     */
    public void setDifferencePrice(Integer differencePrice) {
        this.differencePrice = differencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.discount_price
     *
     * @return the value of activity.discount_price
     *
     * @mbggenerated
     */
    public Integer getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.discount_price
     *
     * @param discountPrice the value for activity.discount_price
     *
     * @mbggenerated
     */
    public void setDiscountPrice(Integer discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.update_time
     *
     * @return the value of activity.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.update_time
     *
     * @param updateTime the value for activity.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.is_effective
     *
     * @return the value of activity.is_effective
     *
     * @mbggenerated
     */
    public Integer getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.is_effective
     *
     * @param isEffective the value for activity.is_effective
     *
     * @mbggenerated
     */
    public void setIsEffective(Integer isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.spread_url
     *
     * @return the value of activity.spread_url
     *
     * @mbggenerated
     */
    public String getSpreadUrl() {
        return spreadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.spread_url
     *
     * @param spreadUrl the value for activity.spread_url
     *
     * @mbggenerated
     */
    public void setSpreadUrl(String spreadUrl) {
        this.spreadUrl = spreadUrl == null ? null : spreadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_id
     *
     * @return the value of activity.create_id
     *
     * @mbggenerated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_id
     *
     * @param createId the value for activity.create_id
     *
     * @mbggenerated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityName=").append(activityName);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", period=").append(period);
        sb.append(", purchasePrice=").append(purchasePrice);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", differencePrice=").append(differencePrice);
        sb.append(", discountPrice=").append(discountPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isEffective=").append(isEffective);
        sb.append(", spreadUrl=").append(spreadUrl);
        sb.append(", createId=").append(createId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}