package com.sysm.back.model;

import java.io.Serializable;
import java.util.Date;

public class GoodsOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.pay_amount
     *
     * @mbggenerated
     */
    private Integer payAmount;

    private String payAmountStr;

    public void setPayAmountStr(String payAmountStr) {
        this.payAmountStr = payAmountStr;
    }

    public void setDifferenceAmountStr(String differenceAmountStr) {
        this.differenceAmountStr = differenceAmountStr;
    }

    public String getPayAmountStr() {
        return payAmountStr;
    }

    public String getDifferenceAmountStr() {
        return differenceAmountStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.difference_amount
     *
     * @mbggenerated
     */
    private Integer differenceAmount;
    private String differenceAmountStr;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.belong_people
     *
     * @mbggenerated
     */
    private Integer belongPeople;
    private String belongPeopleStr;

    public void setBelongPeopleStr(String belongPeopleStr) {
        this.belongPeopleStr = belongPeopleStr;
    }

    public String getBelongPeopleStr() {
        return belongPeopleStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.return_msg
     *
     * @mbggenerated
     */
    private String returnMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.withdraw_status
     *
     * @mbggenerated
     */
    private String withdrawStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.order_id
     *
     * @return the value of goods_order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.order_id
     *
     * @param orderId the value for goods_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.activity_name
     *
     * @return the value of goods_order.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.activity_name
     *
     * @param activityName the value for goods_order.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.activity_id
     *
     * @return the value of goods_order.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.activity_id
     *
     * @param activityId the value for goods_order.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.pay_amount
     *
     * @return the value of goods_order.pay_amount
     *
     * @mbggenerated
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.pay_amount
     *
     * @param payAmount the value for goods_order.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.difference_amount
     *
     * @return the value of goods_order.difference_amount
     *
     * @mbggenerated
     */
    public Integer getDifferenceAmount() {
        return differenceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.difference_amount
     *
     * @param differenceAmount the value for goods_order.difference_amount
     *
     * @mbggenerated
     */
    public void setDifferenceAmount(Integer differenceAmount) {
        this.differenceAmount = differenceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.pay_status
     *
     * @return the value of goods_order.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.pay_status
     *
     * @param payStatus the value for goods_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.remark
     *
     * @return the value of goods_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.remark
     *
     * @param remark the value for goods_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.belong_people
     *
     * @return the value of goods_order.belong_people
     *
     * @mbggenerated
     */
    public Integer getBelongPeople() {
        return belongPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.belong_people
     *
     * @param belongPeople the value for goods_order.belong_people
     *
     * @mbggenerated
     */
    public void setBelongPeople(Integer belongPeople) {
        this.belongPeople = belongPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.create_time
     *
     * @return the value of goods_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.create_time
     *
     * @param createTime the value for goods_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.return_msg
     *
     * @return the value of goods_order.return_msg
     *
     * @mbggenerated
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.return_msg
     *
     * @param returnMsg the value for goods_order.return_msg
     *
     * @mbggenerated
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.trade_type
     *
     * @return the value of goods_order.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.trade_type
     *
     * @param tradeType the value for goods_order.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.ip_address
     *
     * @return the value of goods_order.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.ip_address
     *
     * @param ipAddress the value for goods_order.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.withdraw_status
     *
     * @return the value of goods_order.withdraw_status
     *
     * @mbggenerated
     */
    public String getWithdrawStatus() {
        return withdrawStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.withdraw_status
     *
     * @param withdrawStatus the value for goods_order.withdraw_status
     *
     * @mbggenerated
     */
    public void setWithdrawStatus(String withdrawStatus) {
        this.withdrawStatus = withdrawStatus == null ? null : withdrawStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", activityName=").append(activityName);
        sb.append(", activityId=").append(activityId);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", differenceAmount=").append(differenceAmount);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", remark=").append(remark);
        sb.append(", belongPeople=").append(belongPeople);
        sb.append(", createTime=").append(createTime);
        sb.append(", returnMsg=").append(returnMsg);
        sb.append(", tradeType=").append(tradeType);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", withdrawStatus=").append(withdrawStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}