package com.sysm.back.model;

import java.io.Serializable;
import java.util.Date;

public class ProductKind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kind.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kind.kind_name
     *
     * @mbggenerated
     */
    private String kindName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kind.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kind.is_effective
     *
     * @mbggenerated
     */
    private Byte isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kind.id
     *
     * @return the value of product_kind.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kind.id
     *
     * @param id the value for product_kind.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kind.kind_name
     *
     * @return the value of product_kind.kind_name
     *
     * @mbggenerated
     */
    public String getKindName() {
        return kindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kind.kind_name
     *
     * @param kindName the value for product_kind.kind_name
     *
     * @mbggenerated
     */
    public void setKindName(String kindName) {
        this.kindName = kindName == null ? null : kindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kind.create_time
     *
     * @return the value of product_kind.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kind.create_time
     *
     * @param createTime the value for product_kind.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kind.is_effective
     *
     * @return the value of product_kind.is_effective
     *
     * @mbggenerated
     */
    public Byte getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kind.is_effective
     *
     * @param isEffective the value for product_kind.is_effective
     *
     * @mbggenerated
     */
    public void setIsEffective(Byte isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_kind
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", kindName=").append(kindName);
        sb.append(", createTime=").append(createTime);
        sb.append(", isEffective=").append(isEffective);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}