package com.sysm.back.model;

import java.io.Serializable;
import java.util.Date;

public class SysUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_effective
     *
     * @mbggenerated
     */
    private String isEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.platform_mark
     *
     * @mbggenerated
     */
    private String platformMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mailbox
     *
     * @mbggenerated
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.maturity_time
     *
     * @mbggenerated
     */
    private Date maturityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.belong_software
     *
     * @mbggenerated
     */
    private String belongSoftware;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.belong_agent
     *
     * @mbggenerated
     */
    private String belongAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_effective
     *
     * @return the value of sys_user.is_effective
     *
     * @mbggenerated
     */
    public String getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_effective
     *
     * @param isEffective the value for sys_user.is_effective
     *
     * @mbggenerated
     */
    public void setIsEffective(String isEffective) {
        this.isEffective = isEffective == null ? null : isEffective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone_num
     *
     * @return the value of sys_user.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone_num
     *
     * @param phoneNum the value for sys_user.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.platform_mark
     *
     * @return the value of sys_user.platform_mark
     *
     * @mbggenerated
     */
    public String getPlatformMark() {
        return platformMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.platform_mark
     *
     * @param platformMark the value for sys_user.platform_mark
     *
     * @mbggenerated
     */
    public void setPlatformMark(String platformMark) {
        this.platformMark = platformMark == null ? null : platformMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mailbox
     *
     * @return the value of sys_user.mailbox
     *
     * @mbggenerated
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mailbox
     *
     * @param mailbox the value for sys_user.mailbox
     *
     * @mbggenerated
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ip
     *
     * @return the value of sys_user.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ip
     *
     * @param ip the value for sys_user.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.maturity_time
     *
     * @return the value of sys_user.maturity_time
     *
     * @mbggenerated
     */
    public Date getMaturityTime() {
        return maturityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.maturity_time
     *
     * @param maturityTime the value for sys_user.maturity_time
     *
     * @mbggenerated
     */
    public void setMaturityTime(Date maturityTime) {
        this.maturityTime = maturityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.remark
     *
     * @return the value of sys_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.remark
     *
     * @param remark the value for sys_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.belong_software
     *
     * @return the value of sys_user.belong_software
     *
     * @mbggenerated
     */
    public String getBelongSoftware() {
        return belongSoftware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.belong_software
     *
     * @param belongSoftware the value for sys_user.belong_software
     *
     * @mbggenerated
     */
    public void setBelongSoftware(String belongSoftware) {
        this.belongSoftware = belongSoftware == null ? null : belongSoftware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.belong_agent
     *
     * @return the value of sys_user.belong_agent
     *
     * @mbggenerated
     */
    public String getBelongAgent() {
        return belongAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.belong_agent
     *
     * @param belongAgent the value for sys_user.belong_agent
     *
     * @mbggenerated
     */
    public void setBelongAgent(String belongAgent) {
        this.belongAgent = belongAgent == null ? null : belongAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", createTime=").append(createTime);
        sb.append(", isEffective=").append(isEffective);
        sb.append(", phoneNum=").append(phoneNum);
        sb.append(", platformMark=").append(platformMark);
        sb.append(", mailbox=").append(mailbox);
        sb.append(", ip=").append(ip);
        sb.append(", maturityTime=").append(maturityTime);
        sb.append(", remark=").append(remark);
        sb.append(", belongSoftware=").append(belongSoftware);
        sb.append(", belongAgent=").append(belongAgent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}